development:
  adapter: postgresql
  encoding: unicode
  database: tuner
  pool: 5
  username: zacharystayman
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: tuner_test
  pool: 5
  username: zacharystayman
  host: localhost